/* ----------------------------------------------------------------------------
 * unijp_version.h
 * ----------------------------------------------------------------------------
 * Mastering programmed by YAMASHINA Hio
 *
 * Copyright 2008 YAMASHINA Hio
 * ----------------------------------------------------------------------------
 * This file is autogenerated by autogen.pl.
 * ----------------------------------------------------------------------------
 * $Id$
 * ------------------------------------------------------------------------- */
#ifndef UNIJP_VERSION_H
#define UNIJP_VERSION_H

#ifdef __cplusplus
extern "C"
{
#endif

#define UNIJP_VERSION_STRING "0.46"
#define UNIJP_VERSION_MAJOR  0
#define UNIJP_VERSION_MINOR  46
#define UNIJP_VERSION_PATCH  

#ifdef __cplusplus
}
#endif

#endif /* !defined(UNIJP_VERSION_H) */
/* ----------------------------------------------------------------------------
 * End of File.
 * ------------------------------------------------------------------------- */
